# Site
title:              Zach's Damn Blog
bio:                'coming'
description:        "coming"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/placeholder-big.jpg'
locale:             en_US
url:                http://zachbrowne.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   zachbrowne

# Social
# if you don't have any of social below, comment the line.
google:
  plus:            zachbrowne
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              zachbrowne@gmail.com
twitter:            zachbrowne
facebook:           zachbrowne
github:             zachbrowne
#stackoverflow:      123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           zachbrowne
#xing:              username
instagram:          zachbrowne
#lastfm:             username
tumblr:             zachbrowne
pinterest:          zachbrowne
foursquare:         zachbrowne
#steam:              username
#dribbble:          username
youtube:           designvisibility
#soundcloud:        username
#weibo:             username
flickr:             zachbrowne
#codepen:           username
#keybase:           username
#xmpp:              username@server.com

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
